### ISSUE TITLE
Just a question regarding the bed size you chose

### ISSUE THREAD

**Issue by saskir12** [Alexoko12/Marlin_Config_Lotmaxx_SC-10#3]
So maybe I don't see it right or there is a root cause for this. But why did you write in the configuration.h that the x and y size are 250? Shouldn't it be 235?

**Comment by Alexoko12** [comment]
Hi,
my SC-10 had a 250x250x280 build room. You can shrink the size to 235x235x280 if you don't want to print unintentionally on your bed clamps. Otherwise, I don't know why you want to shrink the bed size. You can always keep a free space near your clamps, when you slice your objects.

If you shrink the bed size, maybe you have to change also something to travel limits. As I haven't flashed for a long time, I am not sure about this part. But give it a try, your printer shouldn't damage from shrinking the bed size.

**Comment by saskir12** [comment]
Strange. You are right. I could have sworn my SC-10 had a 235x235 bed. Sorry for the inconvenience.
